# Generated by Django 5.2 on 2025-05-17 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily Performance Report'), ('difficult', 'Difficult Words Report'), ('quiz', 'Quiz Sessions Report')], default='daily', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.FileField(upload_to='reports/%Y/%m/%d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
