# Generated by Django 5.2 on 2025-05-12 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordChainGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.TextField(blank=True, null=True)),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='wordchain_pictures/%y/%m/%d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordChainEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('position', models.SmallIntegerField()),
                ('word_chain_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordchain.wordchaingame')),
            ],
        ),
    ]
