# Generated by Django 5.2 on 2025-05-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordchaingame',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='wordchain_pictures/%Y/%m/%d'),
        ),
    ]
