# عنوان خادم SonarQube المحلي
sonar.host.url=http://localhost:9000

# مفتاح المشروع الفريد (لا يحتوي مسافات)
sonar.projectKey=louai-org_kelime6

# الاسم الظاهر للمشروع في الواجهة
sonar.projectName=Kelime6

# المسارات التي تريد فحصها (جميع ملفات البايثون)
sonar.sources=.

# استثناء مجلدات الميجريشن وملفات البايت-كود وبيئة العمل الافتراضية
sonar.exclusions=**/migrations/**,**/*.pyc,**/env/**

# تحديد مجلدات الاختبارات لتشملها في التحليل
sonar.tests=.

# تضمين ملفات الاختبار فقط
sonar.test.inclusions=**/tests/**/*.py

# إصدار بايثون المستخدم في المشروع
sonar.python.version=3.8

# مسار تقرير التغطية الذي يولّده pytest (مثلاً)
sonar.python.coverage.reportPaths=coverage.xml
