# Generated by Django 5.2 on 2025-05-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwordprogress',
            name='last_review',
            field=models.DateField(blank=True, null=True),
        ),
    ]
