# Generated by Django 5.2 on 2025-05-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordadder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='picture',
            field=models.ImageField(upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='word',
            name='voice',
            field=models.FileField(upload_to='voices/%Y/%m/%d'),
        ),
    ]
