# Generated by Django 5.2 on 2025-05-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordadder', '0002_alter_word_picture_alter_word_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='word',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='voices/%Y/%m/%d'),
        ),
    ]
