# Generated by Django 5.2 on 2025-05-11 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wordadder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_text', models.CharField(max_length=255)),
                ('attempt_number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LetterFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('letter', models.CharField(max_length=1)),
                ('status', models.CharField(choices=[('correct', 'Correct'), ('present', 'Present'), ('absent', 'Absent')], max_length=7)),
                ('guess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordle.guess')),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_length', models.PositiveSmallIntegerField()),
                ('max_attempts', models.PositiveSmallIntegerField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('solved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordadder.word')),
            ],
        ),
        migrations.AddField(
            model_name='guess',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordle.puzzle'),
        ),
    ]
